export const CATEGORIES = [
  {
    id: "chairs",
    name: "Chairs",
    imageUrl: "https://picsum.photos/seed/chairs/600/800",
  },
  {
    id: "tables",
    name: "Tables",
    imageUrl: "https://picsum.photos/seed/tables/600/800",
  },
  {
    id: "sofas",
    name: "Sofas",
    imageUrl: "https://picsum.photos/seed/sofas/600/800",
  },
  {
    id: "beds",
    name: "Beds",
    imageUrl: "https://picsum.photos/seed/beds/600/800",
  },
  {
    id: "cabinets",
    name: "Cabinets",
    imageUrl: "https://picsum.photos/seed/cabinets/600/800",
  },
  {
    id: "decor",
    name: "Decor",
    imageUrl: "https://picsum.photos/seed/decor/600/800",
  },
];

export const PRODUCTS = [
  // ... (24 products for good filtering/pagination)
  {
    id: 1,
    name: "Nilambur Grand Armchair",
    tagline: "Regal comfort, timeless design.",
    price: 1299,
    category: "Chairs",
    material: "Teak",
    description:
      "Experience unparalleled comfort and regal elegance with the Nilambur Grand Armchair. Hand-carved from the finest solid Nilambur teak, this chair is a testament to traditional craftsmanship and enduring style. Its ergonomic design provides excellent support, while the rich, natural grain of the wood adds a touch of organic warmth to any room. The seat is upholstered with premium, high-density foam and covered in a durable yet soft linen fabric, ensuring it remains a cherished piece for generations. Perfect for a reading nook, living room, or as a statement piece in your study, this armchair is more than just furniture—it's an heirloom in the making. The wood is treated with a natural oil finish to protect it from the elements and highlight its beautiful patterns, making each chair uniquely its own. We believe in sustainability, which is why all our teak is sourced from responsibly managed forests.",
    images: [
      "https://picsum.photos/seed/product1a/800/600",
      "https://picsum.photos/seed/product1b/800/600",
      "https://picsum.photos/seed/product1c/800/600",
    ],
    specs: {
      dimensions: '32"H x 28"W x 30"D',
      finish: "Natural Oil",
      warranty: "Lifetime",
    },
    featured: true,
    popularity: 95,
    createdAt: "2024-07-15T10:00:00Z",
  },
  {
    id: 2,
    name: "Minimalist Teak Dining Table",
    tagline: "Gather around true craftsmanship.",
    price: 2499,
    category: "Tables",
    material: "Teak",
    description:
      "This dining table is the heart of the home. Built to last generations.",
    images: [
      "https://picsum.photos/seed/product2/800/600",
      "https://picsum.photos/seed/product2/800/600",
      "https://picsum.photos/seed/product3/800/600",
    ],
    specs: {
      dimensions: '30"H x 72"W x 36"D',
      finish: "Matte Lacquer",
      warranty: "10 Years",
    },
    featured: true,
    popularity: 92,
    createdAt: "2024-07-10T10:00:00Z",
  },
  {
    id: 3,
    name: "Cloud Comfort Sofa",
    tagline: "Sink into pure bliss.",
    price: 3499,
    category: "Sofas",
    material: "Metal Frame",
    description: "A modern sofa with a durable metal frame and plush cushions.",
    images: ["https://picsum.photos/seed/product3/800/600"],
    specs: {
      dimensions: '34"H x 88"W x 40"D',
      finish: "Powder Coated Black",
      warranty: "5 Years",
    },
    featured: true,
    popularity: 88,
    createdAt: "2024-06-20T10:00:00Z",
  },
  {
    id: 4,
    name: "Serene Platform Bed",
    tagline: "Your personal sanctuary.",
    price: 2199,
    category: "Beds",
    material: "Rosewood",
    description: "Elegant rosewood platform bed for a peaceful night's sleep.",
    images: ["https://picsum.photos/seed/product4/800/600"],
    specs: {
      dimensions: '40"H x 64"W x 84"D',
      finish: "Satin Varnish",
      warranty: "15 Years",
    },
    featured: true,
    popularity: 90,
    createdAt: "2024-05-30T10:00:00Z",
  },
  {
    id: 5,
    name: "Artisan Display Cabinet",
    tagline: "Showcase your treasures.",
    price: 1899,
    category: "Cabinets",
    material: "Mahogany",
    description: "A beautiful mahogany cabinet with glass doors.",
    images: ["https://picsum.photos/seed/product5/800/600"],
    specs: {
      dimensions: '72"H x 40"W x 16"D',
      finish: "Glossy Red",
      warranty: "10 Years",
    },
    featured: false,
    popularity: 75,
    createdAt: "2024-07-01T10:00:00Z",
  },
  {
    id: 6,
    name: "Sculpted Teak Vase",
    tagline: "Nature's art form.",
    price: 299,
    category: "Decor",
    material: "Teak",
    description: "Hand-sculpted vase from a single piece of teak.",
    images: ["https://picsum.photos/seed/product6/800/600"],
    specs: { dimensions: '12"H x 6"W', finish: "Beeswax", warranty: "1 Year" },
    featured: false,
    popularity: 85,
    createdAt: "2024-07-18T10:00:00Z",
  },
  {
    id: 7,
    name: "Rosewood Lounge Chair",
    tagline: "Elegance in repose.",
    price: 1599,
    category: "Chairs",
    material: "Rosewood",
    description: "A stunning lounge chair with rich, dark rosewood tones.",
    images: ["https://picsum.photos/seed/product7/800/600"],
    specs: {
      dimensions: '30"H x 30"W x 32"D',
      finish: "High Gloss",
      warranty: "20 Years",
    },
    featured: false,
    popularity: 80,
    createdAt: "2024-04-10T10:00:00Z",
  },
  {
    id: 8,
    name: "Mahogany Coffee Table",
    tagline: "The centerpiece of conversation.",
    price: 999,
    category: "Tables",
    material: "Mahogany",
    description: "A classic coffee table with intricate carvings.",
    images: ["https://picsum.photos/seed/product8/800/600"],
    specs: {
      dimensions: '18"H x 48"W x 24"D',
      finish: "Dark Stain",
      warranty: "10 Years",
    },
    featured: false,
    popularity: 78,
    createdAt: "2024-06-15T10:00:00Z",
  },
  // Add more products to reach 24 total
  {
    id: 9,
    name: "Luxe Velvet Sofa",
    tagline: "Opulence meets comfort.",
    price: 3999,
    category: "Sofas",
    material: "Metal Frame",
    description: "Soft velvet upholstery on a sturdy frame.",
    images: ["https://picsum.photos/seed/product9/800/600"],
    specs: {
      dimensions: '32"H x 96"W x 42"D',
      finish: "Gold Plated",
      warranty: "7 Years",
    },
    featured: false,
    popularity: 82,
    createdAt: "2023-11-20T10:00:00Z",
  },
  {
    id: 10,
    name: "Canopy Dream Bed",
    tagline: "Sleep like royalty.",
    price: 3199,
    category: "Beds",
    material: "Teak",
    description: "A four-poster bed made from the finest teak.",
    images: ["https://picsum.photos/seed/product10/800/600"],
    specs: {
      dimensions: '85"H x 80"W x 88"D',
      finish: "Natural Oil",
      warranty: "Lifetime",
    },
    featured: false,
    popularity: 89,
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: 11,
    name: "Modern Media Cabinet",
    tagline: "Sleek and functional.",
    price: 1499,
    category: "Cabinets",
    material: "Metal Frame",
    description: "A low-profile cabinet for your entertainment system.",
    images: ["https://picsum.photos/seed/product11/800/600"],
    specs: {
      dimensions: '24"H x 60"W x 18"D',
      finish: "Matte Black",
      warranty: "5 Years",
    },
    featured: false,
    popularity: 70,
    createdAt: "2024-03-05T10:00:00Z",
  },
  {
    id: 12,
    name: "Geometric Wood Panel Art",
    tagline: "Wall decor redefined.",
    price: 499,
    category: "Decor",
    material: "Rosewood",
    description: "Interlocking rosewood panels create a stunning visual.",
    images: ["https://picsum.photos/seed/product12/800/600"],
    specs: { dimensions: '36"H x 36"W', finish: "Satin", warranty: "2 Years" },
    featured: true,
    popularity: 86,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 13,
    name: "Executive Teak Desk",
    tagline: "Command your workspace.",
    price: 2899,
    category: "Tables",
    material: "Teak",
    description: "A large, imposing desk with ample storage.",
    images: ["https://picsum.photos/seed/product13/800/600"],
    specs: {
      dimensions: '31"H x 66"W x 30"D',
      finish: "Leather Inlay",
      warranty: "25 Years",
    },
    featured: false,
    popularity: 84,
    createdAt: "2024-04-22T10:00:00Z",
  },
  {
    id: 14,
    name: "Petite Accent Chair",
    tagline: "Small space, big style.",
    price: 799,
    category: "Chairs",
    material: "Mahogany",
    description: "Perfect for corners or as extra seating.",
    images: ["https://picsum.photos/seed/product14/800/600"],
    specs: {
      dimensions: '29"H x 24"W x 25"D',
      finish: "Cherry Stain",
      warranty: "5 Years",
    },
    featured: false,
    popularity: 77,
    createdAt: "2023-12-10T10:00:00Z",
  },
  {
    id: 15,
    name: "Convertible Daybed Sofa",
    tagline: "Versatility and comfort.",
    price: 2999,
    category: "Sofas",
    material: "Teak",
    description: "A stylish sofa that easily converts into a daybed.",
    images: ["https://picsum.photos/seed/product15/800/600"],
    specs: {
      dimensions: '33"H x 80"W x 38"D',
      finish: "Light Varnish",
      warranty: "10 Years",
    },
    featured: false,
    popularity: 81,
    createdAt: "2024-06-25T10:00:00Z",
  },
  {
    id: 16,
    name: "Floating Nightstand",
    tagline: "Modern bedside elegance.",
    price: 599,
    category: "Beds",
    material: "Rosewood",
    description: "Wall-mounted nightstand with a single drawer.",
    images: ["https://picsum.photos/seed/product16/800/600"],
    specs: {
      dimensions: '10"H x 20"W x 14"D',
      finish: "Matte",
      warranty: "5 Years",
    },
    featured: false,
    popularity: 79,
    createdAt: "2024-07-20T10:00:00Z",
  },
  {
    id: 17,
    name: "Library Bookcase",
    tagline: "A home for your stories.",
    price: 3299,
    category: "Cabinets",
    material: "Mahogany",
    description: "A grand, floor-to-ceiling bookcase.",
    images: ["https://picsum.photos/seed/product17/800/600"],
    specs: {
      dimensions: '96"H x 48"W x 15"D',
      finish: "Dark Walnut",
      warranty: "20 Years",
    },
    featured: false,
    popularity: 83,
    createdAt: "2023-10-01T10:00:00Z",
  },
  {
    id: 18,
    name: "Carved Teak Mirror",
    tagline: "Reflect your style.",
    price: 699,
    category: "Decor",
    material: "Teak",
    description: "A large mirror framed with intricately carved teak.",
    images: ["https://picsum.photos/seed/product18/800/600"],
    specs: {
      dimensions: '48"H x 30"W',
      finish: "Weathered Gray",
      warranty: "3 Years",
    },
    featured: false,
    popularity: 87,
    createdAt: "2024-07-22T10:00:00Z",
  },
  {
    id: 19,
    name: "Teak Bar Stool",
    tagline: "Elevated seating.",
    price: 499,
    category: "Chairs",
    material: "Teak",
    description: "Sleek and sturdy bar stool for your kitchen island.",
    images: ["https://picsum.photos/seed/product19/800/600"],
    specs: {
      dimensions: '30"H x 18"W x 18"D',
      finish: "Natural",
      warranty: "10 Years",
    },
    featured: false,
    popularity: 76,
    createdAt: "2024-07-12T10:00:00Z",
  },
  {
    id: 20,
    name: "Expandable Dining Table",
    tagline: "For gatherings big and small.",
    price: 3199,
    category: "Tables",
    material: "Rosewood",
    description: "A versatile table that expands to seat 12.",
    images: ["https://picsum.photos/seed/product20/800/600"],
    specs: {
      dimensions: '30"H x 80-110"W x 40"D',
      finish: "Satin",
      warranty: "15 Years",
    },
    featured: false,
    popularity: 91,
    createdAt: "2024-05-11T10:00:00Z",
  },
  {
    id: 21,
    name: "Modular Sectional Sofa",
    tagline: "Design your own comfort.",
    price: 4599,
    category: "Sofas",
    material: "Metal Frame",
    description: "A configurable sectional to fit any space.",
    images: ["https://picsum.photos/seed/product21/800/600"],
    specs: {
      dimensions: "Varies by configuration",
      finish: "Chrome Legs",
      warranty: "10 Years",
    },
    featured: true,
    popularity: 93,
    createdAt: "2024-03-28T10:00:00Z",
  },
  {
    id: 22,
    name: "Upholstered Headboard",
    tagline: "A touch of softness.",
    price: 899,
    category: "Beds",
    material: "Metal Frame",
    description: "A plush, button-tufted headboard.",
    images: ["https://picsum.photos/seed/product22/800/600"],
    specs: {
      dimensions: '55"H x 62"W',
      finish: "Linen Fabric",
      warranty: "5 Years",
    },
    featured: false,
    popularity: 74,
    createdAt: "2024-07-08T10:00:00Z",
  },
  {
    id: 23,
    name: "Entryway Console Cabinet",
    tagline: "A warm welcome.",
    price: 1399,
    category: "Cabinets",
    material: "Teak",
    description: "A slim cabinet perfect for hallways.",
    images: ["https://picsum.photos/seed/product23/800/600"],
    specs: {
      dimensions: '32"H x 48"W x 14"D',
      finish: "Light Stain",
      warranty: "15 Years",
    },
    featured: false,
    popularity: 80,
    createdAt: "2024-06-01T10:00:00Z",
  },
  {
    id: 24,
    name: "Set of 3 Teak Bowls",
    tagline: "Organic elegance.",
    price: 199,
    category: "Decor",
    material: "Teak",
    description: "Nesting bowls for decoration or serving.",
    images: ["https://picsum.photos/seed/product24/800/600"],
    specs: {
      dimensions: "Varying sizes",
      finish: "Food-safe oil",
      warranty: "1 Year",
    },
    featured: false,
    popularity: 72,
    createdAt: "2024-07-25T10:00:00Z",
  },
];
