export const themeColors = {
  blackWhite: {
    background: "#FFFFFF",
    text: "#1A1A1A",
    accent: "#D4AF37",
    secondary: "#F5F5DC",
    cardBg: "#FAFAFA",
    border: "#E5E5E5",
  },
  earthyWarm: {
    background: "#F5F1E8",
    text: "#3E2723",
    accent: "#8D6E63",
    secondary: "#D7CCC8",
    cardBg: "#EFEBE9",
    border: "#BCAAA4",
  },
  modernMinimal: {
    background: "#F5F5F5",
    text: "#2C2C2C",
    accent: "#000000",
    secondary: "#E0E0E0",
    cardBg: "#FFFFFF",
    border: "#BDBDBD",
  },

  blackWhited: {
    background: "bg-white",
    text: "text-black",
    textMuted: "text-gray-500",
    textAccent: "text-black",
    border: "border-gray-300",
    card: {
      background: "bg-white",
      border: "border-black",
      shadow: "shadow-none",
      text: "text-black",
      hover: "hover:shadow-lg",
    },
    button: {
      primary: "bg-black",
      primaryText: "text-white",
      primaryHover: "hover:bg-gray-800",
      secondary: "bg-white border border-black",
      secondaryText: "text-black",
      secondaryHover: "hover:bg-gray-100",
    },
    header: {
      background: "bg-white",
      text: "text-black",
      border: "border-b border-black",
    },
    input: {
      background: "bg-white",
      text: "text-black",
      border: "border-black",
      focus: "focus:ring-black focus:border-black",
      placeholder: "placeholder-gray-500",
    },
  },

  modernMinimal: {
    background: "bg-gray-50",
    text: "text-gray-800",
    textMuted: "text-gray-600",
    textAccent: "text-blue-600",
    border: "border-gray-200",
    card: {
      background: "bg-white",
      border: "border-gray-200",
      shadow: "shadow-md",
      text: "text-gray-800",
      hover: "hover:shadow-xl",
    },
    button: {
      primary: "bg-blue-600",
      primaryText: "text-white",
      primaryHover: "hover:bg-blue-700",
      secondary: "bg-white border border-gray-300",
      secondaryText: "text-gray-800",
      secondaryHover: "hover:bg-gray-100",
    },
    header: {
      background: "bg-white",
      text: "text-gray-800",
      border: "border-b border-gray-200",
    },
    input: {
      background: "bg-white",
      text: "text-gray-900",
      border: "border-gray-300",
      focus: "focus:ring-blue-500 focus:border-blue-500",
      placeholder: "placeholder-gray-400",
    },
  },

  luxuryDark: {
    background: "bg-black",
    text: "text-gray-300",
    textMuted: "text-gray-400",
    textAccent: "text-amber-400",
    border: "border-gray-700",
    card: {
      background: "bg-gray-900",
      border: "border-gray-700",
      shadow: "shadow-lg shadow-amber-500/5",
      text: "text-gray-200",
      hover: "hover:border-amber-400",
    },
    button: {
      primary: "bg-amber-400",
      primaryText: "text-black",
      primaryHover: "hover:bg-amber-300",
      secondary: "bg-transparent border border-amber-400",
      secondaryText: "text-amber-400",
      secondaryHover: "hover:bg-amber-400 hover:text-black",
    },
    header: {
      background: "bg-black",
      text: "text-gray-200",
      border: "border-b border-gray-800",
    },
    input: {
      background: "bg-gray-800",
      text: "text-gray-200",
      border: "border-gray-600",
      focus: "focus:ring-amber-500 focus:border-amber-500",
      placeholder: "placeholder-gray-500",
    },
  },
};
